
server:
  port: 8080

spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: #clientID
            client-secret: #clientSecret
            authorization: authorization_code
            scope: openid
        provider:
          keycloak:
            issuer-uri: http://localhost:8081/realms/ #realmName
            user-name-attribute: preferred_username
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/ #realmName
